### ISSUE TITLE
Code not working because of a typo

### ISSUE THREAD

**Issue by mrgiel** [cheezytony/vue3-form#1]
Hey man,
I had some problems setting up ur form. I found out it was because of a typo.
You are using getFieldErrors, but that should be getFieldError. Might be great if you update it, so new developers (like me) won't have this struggle.

**Comment by cheezytony** [comment]
Thanks so much, I'll fix it right away

**Comment by cheezytony** [comment]
@mrgiel Feel free to open prs or issues, if there are more improvements you'd want me to make.
